import { createUser } from "@/graphql/modules/auth/users/user.services";

const run = async () => {
  const users = [
    {
      username: "Budi12345",
      password: "Budi12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Budi",
        last_name: "Santoso",
        date_of_birth: new Date("1985-05-15"),
        gender: "Male",
        email: "budi.santoso@example.com",
        phone: "081234567890",
        address: "Jl. Merdeka No. 1",
        city: "Jakarta",
        state: "DKI Jakarta",
        postal_code: "10110",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Married",
        occupation: "Engineer",
      },
    },
    {
      username: "Sari12345",
      password: "Sari12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Sari",
        last_name: "Mardiani",
        date_of_birth: new Date("1990-03-20"),
        gender: "Female",
        email: "sari.mardiani@example.com",
        phone: "082345678901",
        address: "Jl. Raya No. 2",
        city: "Bandung",
        state: "Jawa Barat",
        postal_code: "40111",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Single",
        occupation: "Designer",
      },
    },
    {
      username: "Andi12345",
      password: "Andi12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Andi",
        last_name: "Kurniawan",
        date_of_birth: new Date("1988-07-08"),
        gender: "Male",
        email: "andi.kurniawan@example.com",
        phone: "083456789012",
        address: "Jl. Cendana No. 3",
        city: "Yogyakarta",
        state: "DI Yogyakarta",
        postal_code: "55222",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Married",
        occupation: "Teacher",
      },
    },
    {
      username: "Lina12345",
      password: "Lina12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Lina",
        last_name: "Wati",
        date_of_birth: new Date("1995-11-30"),
        gender: "Female",
        email: "lina.wati@example.com",
        phone: "084567890123",
        address: "Jl. Pahlawan No. 4",
        city: "Surabaya",
        state: "Jawa Timur",
        postal_code: "60225",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Single",
        occupation: "Student",
      },
    },
    {
      username: "Faisal12345",
      password: "Faisal12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Faisal",
        last_name: "Rahman",
        date_of_birth: new Date("1992-02-12"),
        gender: "Male",
        email: "faisal.rahman@example.com",
        phone: "085678901234",
        address: "Jl. Anggrek No. 5",
        city: "Medan",
        state: "Sumatera Utara",
        postal_code: "20111",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Married",
        occupation: "Doctor",
      },
    },
    {
      username: "Diana12345",
      password: "Diana12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Diana",
        last_name: "Putri",
        date_of_birth: new Date("1994-04-25"),
        gender: "Female",
        email: "diana.putri@example.com",
        phone: "086789012345",
        address: "Jl. Kenanga No. 6",
        city: "Bali",
        state: "Bali",
        postal_code: "80222",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Single",
        occupation: "Artist",
      },
    },
    {
      username: "Rudi12345",
      password: "Rudi12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Rudi",
        last_name: "Setiawan",
        date_of_birth: new Date("1987-09-09"),
        gender: "Male",
        email: "rudi.setiawan@example.com",
        phone: "087890123456",
        address: "Jl. Melati No. 7",
        city: "Semarang",
        state: "Jawa Tengah",
        postal_code: "50111",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Married",
        occupation: "Programmer",
      },
    },
    {
      username: "Putri12345",
      password: "Putri12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Putri",
        last_name: "Nugraha",
        date_of_birth: new Date("1993-08-15"),
        gender: "Female",
        email: "putri.nugraha@example.com",
        phone: "088901234567",
        address: "Jl. Durian No. 8",
        city: "Palembang",
        state: "Sumatera Selatan",
        postal_code: "30111",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Single",
        occupation: "Nurse",
      },
    },
    {
      username: "Tari12345",
      password: "Tari12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Tari",
        last_name: "Sari",
        date_of_birth: new Date("1996-12-20"),
        gender: "Female",
        email: "tari.sari@example.com",
        phone: "089012345678",
        address: "Jl. Cempaka No. 9",
        city: "Makassar",
        state: "Sulawesi Selatan",
        postal_code: "90222",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Single",
        occupation: "Writer",
      },
    },
    {
      username: "Adi12345",
      password: "Adi12345",
      role: "client",
      is_active: true,
      biodata: {
        first_name: "Adi",
        last_name: "Prabowo",
        date_of_birth: new Date("1989-06-18"),
        gender: "Male",
        email: "adi.prabowo@example.com",
        phone: "090123456789",
        address: "Jl. Sukun No. 10",
        city: "Bandung",
        state: "Jawa Barat",
        postal_code: "40222",
        country: "Indonesia",
        nationality: "Indonesian",
        marital_status: "Married",
        occupation: "Chef",
      },
    },
  ];

  for (const user of users) {
    try {
      const createdUser = await createUser(
        user.username,
        user.password,
        user.role,
        user.is_active,
        user.biodata
      );
    } catch (error) {
      console.error("Error:", error);
    }
  }
};

run();

// cmd : npx ts-node -r tsconfig-paths/register src/migrations/createData.ts
